name: Docker Security Scan

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'apps/server/**'
      - 'apps/server/Dockerfile'
  pull_request:
    branches: [ main, develop ]
    paths: 
      - 'apps/server/**'
      - 'apps/server/Dockerfile'

jobs:
  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.18

      - name: Install dependencies
        run: |
          cd apps/server
          bun install --frozen-lockfile

      - name: Build Docker image
        run: |
          cd apps/server
          docker build -t neostock-server:latest .

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'neostock-server:latest'
          format: 'sarif'
          output: 'docker-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Docker Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('docker-trivy-results.sarif') != ''
        with:
          sarif_file: 'docker-trivy-results.sarif'

      - name: Run Docker Bench Security
        run: |
          docker run --rm --net host --pid host --userns host --cap-add audit_control \
            -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
            -v /var/lib:/var/lib:ro \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v /usr/lib/systemd:/usr/lib/systemd:ro \
            -v /etc:/etc:ro \
            --label docker_bench_security \
            docker/docker-bench-security || true

      - name: Scan with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: apps/server/Dockerfile
          failure-threshold: error
          no-fail: false